import "~/styles/globals.css";

import { type Metadata } from "next";
import { Merriweather, Noto_Serif, Kanit } from "next/font/google";

import { TRPCReactProvider } from "~/trpc/react";
import { AppRouterCacheProvider } from "@mui/material-nextjs/v15-appRouter";
import Footer from "./_components/footer";
import Header from "./_components/header";

export const metadata: Metadata = {
  title: "Create T3 App",
  description: "Generated by create-t3-app",
  icons: [{ rel: "icon", url: "/favicon.ico" }],
};

const merriweather = Merriweather({
  subsets: ["latin"],
  weight: ["400", "700"],
});

const notoSerif = Noto_Serif({
  subsets: ["latin"],
  weight: ["400", "700"],
});

const kanit = Kanit({
  subsets: ["latin"],
  weight: ["400"],
});

export default function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  return (
    <html lang="en" className={`scroll-smooth ${notoSerif.className}`}>
      <body>
        <Header></Header>
        <AppRouterCacheProvider options={{ enableCssLayer: true }}>
          {children}
        </AppRouterCacheProvider>
        <Footer></Footer>
      </body>
    </html>
  );
}
